### ISSUE TITLE
蹲饼无法抓取到微博图片

### ISSUE THREAD

**Issue by RovingAimer** [cssxsh/arknights-helper#1]
RT，因为新浪有不同图床？是否是因为存在wx1 wx2 wx3 wx4等url导致图片无法保存到本地？
我这里在WeiboData下创建了图片名的文件夹，但没有保存图片，并且bot显示添加图片失败。

**Comment by cssxsh** [comment]
> RT，因为新浪有不同图床？是否是因为存在wx1 wx2 wx3 wx4等url导致图片无法保存到本地？
> 我这里在WeiboData下创建了图片名的文件夹，但没有保存图片，并且bot显示添加图片失败。

本来应该创建父母路径的文件夹的，不小心写成当前路径文件夹了

**Comment by cssxsh** [comment]
#2 
[修复文件创建](https://github.com/cssxsh/arknights-helper/pull/2/commits/ea867f3426296903e6c001b613e1f598018fb761#diff-f60b65c82394800f7d52d97c7ba770cd771131da8532a62045580b7e51c2ec88)
