### ISSUE TITLE
无法回答问题

### ISSUE THREAD

**Issue by mojizooo** [cssxsh/arknights-helper#13]
bot发了问题之后无法对回复做出反应，只会等到时间结束发送回答超时(其他所有指令都有效)

**Comment by cssxsh** [comment]
最新版 v1.2.1-dev-5 答题者也需要答题权限 请确认 答题者拥有权限

**Comment by cssxsh** [comment]
> 最新版 v1.2.1-dev-5 答题者也需要答题权限 请确认 答题者拥有权限

这或许是个多余的特性，在 `v1.2.1-dev-6` 中 还是去掉比较好

**Comment by mojizooo** [comment]
答题权限是哪一个 我给了所有成员*:*也没有用






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cssxsh/arknights-helper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月25日(星期五) 晚上7:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cssxsh/arknights-helper] 无法回答问题 (#13)





 
最新版 v1.2.1-dev-5 答题者也需要答题权限 请确认 答题者拥有权限

**Comment by cssxsh** [comment]
> 答题权限是哪一个 我给了所有成员*:*也没有用
那就试试 预发布的 `v1.2.1-dev-6` 吧这个版本去除了答题者的权限验证
