### ISSUE TITLE
插件无响应

### ISSUE THREAD

**Issue by 1072324725** [cssxsh/arknights-helper#29]
用/抽卡 十连这个指令没有反应，其他的指令也没有反应，jar已经放进Marai-plugins里了，data里也自动下载了文件包。是我漏做了啥吗大佬？
![image](https://user-images.githubusercontent.com/69476228/143530023-7129aa74-3c2c-45ef-b043-b2815525d5ad.png)

**Comment by cssxsh** [comment]
https://github.com/cssxsh/arknights-helper/blob/c9e8ca8bda0523ac8aac285a070541b88a3fba15/readme.md?plain=1#L11-L15
