### ISSUE TITLE
合成玉出现负数

### ISSUE THREAD

**Issue by qmzola** [cssxsh/arknights-helper#3]
啊这，还能负数的吗![-2503971c4f427c9.png](https://user-images.githubusercontent.com/75173095/118274151-5b807880-b4f7-11eb-8c0b-16526ed1fb25.png)

**Comment by cssxsh** [comment]
是可以的
群聊模式中抢答存在惩罚机制，会扣除合成玉

**Comment by qmzola** [comment]
> 是可以的
> 群聊模式中抢答存在惩罚机制，会扣除合成玉

az
