### ISSUE TITLE
缓存清理

### ISSUE THREAD

**Issue by AquamarineCyan** [cssxsh/arknights-helper#30]
缓存清理，尤其WeiboData下，目前只能手动删除，是否能提供过期时间自动清理或者手动调取命令的形式

**Comment by cssxsh** [comment]
考虑提供 `/data clear` 命令的形式 清理缓存

**Comment by cssxsh** [comment]
with <https://github.com/cssxsh/arknights-helper/releases/tag/v1.3.11>

**Comment by AquamarineCyan** [comment]
已更新，可以运行
