### ISSUE TITLE
mcl启动时长时间报connection reset

### ISSUE THREAD

**Issue by Beacon0219** [cssxsh/arknights-helper#33]
W/arknights-helper: Downloader Ignore java.net.SocketException: Connection reset
大概要报20min左右，然后突然就没有了....

**Comment by cssxsh** [comment]
插件会在启动的时候, 插件会检查一下数据是否有新版本，你的网络环境可能有影响

**Comment by cssxsh** [comment]
关于加载问题，https://github.com/cssxsh/arknights-helper/releases/tag/v1.4.0 有优化
