### ISSUE TITLE
给予权限后，指令无反应

### ISSUE THREAD

**Issue by RaTaiHok** [cssxsh/arknights-helper#34]
我在输入/perm permit u* xyz.cssxsh.mirai.plugin.arknights-helper:* 之后后台有回复OK
然后在config的yml中输入了群号 但是在重启框架之后又恢复了初始的{}
指令也无法正常触发

**Comment by RaTaiHok** [comment]
不知道是不是一直在加载 但是在刚开插件的时候有显示加载成功 也没有更新提示

**Comment by cssxsh** [comment]
请确认 已经安装了 chat-command

**Comment by RaTaiHok** [comment]
> 请确认 已经安装了 chat-command

额是这样的 因为其他功能也在用，chat-command一直都是正常状态 我现在很疑惑（

**Comment by cssxsh** [comment]
插件要等 `ExcelData 数据加载完毕, 版本 ...` 等字样的日志出现，表明数据加载完成时才会注册指令

关于加载问题，https://github.com/cssxsh/arknights-helper/releases/tag/v1.4.0 有优化
