### ISSUE TITLE
抽卡指令似乎存在错误/以及语音发送失败

### ISSUE THREAD

**Issue by Cha-Sir** [cssxsh/arknights-helper#39]
如题，所有指令均能运行正常，但与说明文档不同，抽卡指令只能通过/ark-gacha前缀执行，/gacha和/抽卡均无反应

语音qq群内显示发送，但是是裂开的（1秒的空语音，但是后台已经可以看到生成的语音文件）

**Comment by cssxsh** [comment]
关于语音发送，你需要这个 https://github.com/project-mirai/mirai-silk-converter

**Comment by cssxsh** [comment]
https://github.com/project-mirai/mirai-silk-converter/issues/7
