### ISSUE TITLE
风控校验失败

### ISSUE THREAD

**Issue by ghost** [cssxsh/arknights-helper#40]
Running MiraiConsole v2.16.0, built on 2023-10-20 06:28:10.
Frontend Terminal: version 2.16.0, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: Chat Command v0.6.0, fix-protocol-version v1.13.0, mirai-login-solver-sakura v0.0.12, com.github.eiriksgata.rulateday-dice v0.5.2, arknights-helper v2.2.1, MCL Addon v2.1.1

Object Pending Finalization Count: 0
                 committed |  init  |   used   |   max
    Heap Memory:  608.0MB  | 1.0GB  | 186.05MB | 15.93GB
Non-Heap Memory: 130.06MB  | 7.31MB | 126.74MB |   -1

=================================

具体问题为使用抽卡指令提示风控校验失败，打开控制台的链接网页展示内容如下:

https://api.bilibili.com/x/space/wbi/arc/search?mid=161775300&ps=50&pn=1&order=pubdate&tid=3&jsonp=jsonp&wts=1701837061&w_rid=1250e3dd1dff899b3cda023f44055519
↓↓↓↓
{
    "code": -352,
    "message": "风控校验失败",
    "ttl": 1,
    "data": {
        "v_voucher": "voucher_2d1ff686-f09f-416d-94f6-d94573c29a96"
    }
}

**Comment by cssxsh** [comment]
B站反爬机制，无法简单处理
